modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/RakSrinaNa/OverpoweredMending/issues"
displayURL="https://github.com/RakSrinaNa/OverpoweredMending"
logoFile="logo.png"
# credits=""
authors="RakSrinaNa"

[[mods]] #mandatory
	modId="overpowered_mending"
	version="${file.jarVersion}"
	displayName="Overpowered Mending"
	updateJSONURL="https://raw.githubusercontent.com/RakSrinaNa/OverpoweredMending/1.14.4/update.json"
	description='''Changes Mending behaviour to repair what is in your inventory and need it the most. No need to have it equipped anymore.'''

[[dependencies.overpowered_mending]]
    modId="forge"
    mandatory=true
    versionRange="[28.1.47,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.overpowered_mending]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
