modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/${project.repoUser}/${project.repoName}/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/overpowered-mending"
logoFile="logo.png"
# credits=""
authors="RakSrinaNa"
license = "GPL-3.0"

[[mods]] #mandatory
	modId="${project.mod_id}"
    version="${project.version}"
	displayName="${project.modName}"
    updateJSONURL="https://raw.githubusercontent.com/${project.repoUser}/${project.repoName}/${project.minecraft_version}-forge/update.json"
	description='''Changes Mending behaviour to repair what is in your inventory and need it the most. No need to have it equipped anymore.'''

[[dependencies.overpowered_mending]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.overpowered_mending]]
    modId="minecraft"
    mandatory=true
    versionRange="[${project.minecraft_version}]"
    ordering="NONE"
    side="BOTH"
