modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/RakSrinaNa/OverpoweredMending/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/overpowered-mending"
logoFile="logo.png"
# credits=""
authors="RakSrinaNa"

[[mods]] #mandatory
	modId="overpowered_mending"
	version="${file.jarVersion}"
	displayName="Overpowered Mending"
	updateJSONURL="https://raw.githubusercontent.com/RakSrinaNa/OverpoweredMending/1.16.1/update.json"
	description='''Changes Mending behaviour to repair what is in your inventory and need it the most. No need to have it equipped anymore.'''

[[dependencies.overpowered_mending]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.0,)"
    ordering="NONE"
	side="BOTH"
[[dependencies.overpowered_mending]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
